name = "LightPSRIO"
uuid = "fab0d976-c881-4233-b6b1-4ff1009f1ddc"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LuaNova = "faa88067-b4cd-4998-97ac-8175b58d6ef9"
PSRDates = "0b292b47-0876-4319-b6bc-6a18552db160"
Patchwork = "89290475-19d9-4972-8f76-8da21b5d05c1"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Quiver = "cdbb3f72-2527-4dbd-9d0e-93533a5519ac"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources.PSRDates]
url = "https://github.com/psrenergy/PSRDates.jl"

[compat]
ArgParse = "1"
JSON = "0.21, 1.0"
Patchwork = "0.1.4"
Statistics = "1"
Unitful = "1.25.1"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DataFrames", "Random", "Test"]
