[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
PSRContinuousDeployment = "f0087d4c-ff99-426e-93c9-09c1a88911f9"

[sources]
PSRContinuousDeployment = {url = "https://github.com/psrenergy/PSRContinuousDeployment.jl"}